controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage: 
    path: /home
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults: 
        route: app_home
        keepQueryParams: true
        permanent: true

